api:
  identifier: "anydev-authserver-mircoservices"
  port: 5001

logger:
  options:
    level: trace

mongodb:
  url: "mongodb://127.0.0.1:27017"
  database: "anydev"
  options:
    useUnifiedTopology: true
    useNewUrlParser: true

jwt:
  accessTokenSecret: "0d7c5c5f-768c-4d98-8900-13aadaa21937"
  refreshTokenSecret: "1a7v8c0l-391k-1f82-4492-tha3taa11334"
  accessTokenLife: "30d"
  refreshTokenLife: 2592000
